# wordpress with ansible

---
- hosts: cent8
  become: yes
  vars_prompt:
    - name: "domain_name"
      prompt: "Domain name: "
      private: no
    - name: "db_root_password"
      prompt: "Database root password:"
      private: no
    - name: "db_name"
      prompt: "Wordpress database name:"
      private: no
    - name: "db_user"
      prompt: "Wordpress database user:"
      private: no
    - name: "db_user_password"
      prompt: "Wordpress database user password:"
      private: no
  roles:
    - mariadb
    - php
    - nginx
